title: A.J. Brown
subtitle: Software Scalability and Platforms Architect
email: aj@ajbrown.org
description: > # this means to ignore newlines until "baseurl:"
  A.J. Brown is an AWS Certified Solutions Architect and Java developer from Dayton Ohio. He's passionate about software
  craftsmanship, developer productivity, microservice platforms, and Amazon Web Services.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ajbrown.org" # the base hostname & protocol for your site
twitter_username: adrianjbrown
github_username:  ajbrown
linkedin_username: ajbrown

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
